name: telpo_flutter_sdk
description: A Flutter plugin for Telpo devices for handling connectivity and communication with the thermal printer.
version: 0.1.2
homepage: https://github.com/AL-ventures/telpo-flutter-sdk

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: me.aljan.telpo_flutter_sdk
        pluginClass: TelpoFlutterSdkPlugin