class ASCII {
  static const int NUL = 0x00;
  static const int SOH = 0x01;
  static const int STX = 0x02;
  static const int ETX = 0x03;
  static const int EOT = 0x04;
  static const int ENQ = 0x05;
  static const int ACK = 0x06;
  static const int BEL = 0x07;
  static const int BS = 0x08;
  static const int HT = 0x09;
  static const int LF = 0x0A;
  static const int VT = 0x0B;
  static const int FF = 0x0C;
  static const int CR = 0x0D;
  static const int SO = 0x0E;
  static const int SI = 0x0F;
  static const int DLE = 0x10;
  static const int DC1 = 0x11;
  static const int DC2 = 0x12;
  static const int DC3 = 0x13;
  static const int DC4 = 0x14;
  static const int NAK = 0x15;
  static const int SYN = 0x16;
  static const int ETB = 0x17;
  static const int CAN = 0x18;
  static const int EM = 0x19;
  static const int SUB = 0x1A;
  static const int ESC = 0x1B;
  static const int FS = 0x1C;
  static const int GS = 0x1D;
  static const int RS = 0x1E;
  static const int US = 0x1F;

  static const int SPACE = 0x20; // ' '
  static const int EXCLAMATION = 0x21; // '!'
  static const int QUOTATION = 0x22; // '"'
  static const int NUMBER = 0x23; // '#'
  static const int DOLLAR = 0x24; // '$'
  static const int PERCENT = 0x25; // '%'
  static const int AMPERSAND = 0x26; // '&'
  static const int APOSTROPHE = 0x27; // '''
  static const int OPENBRACKET = 0x28; // '('
  static const int CLOSEBRACKET = 0x29; // ')'
  static const int ASTERISK = 0x2A; // '*'
  static const int PLUS = 0x2B; // '+'
  static const int COMMA = 0x2C; // ','
  static const int MINUS = 0x2D; // '-'
  static const int DOT = 0x2E; // '.'
  static const int SLASH = 0x2F; // '/'

  static const int n0 = 0x30;
  static const int n1 = 0x31;
  static const int n2 = 0x32;
  static const int n3 = 0x33;
  static const int n4 = 0x34;
  static const int n5 = 0x35;
  static const int n6 = 0x36;
  static const int n7 = 0x37;
  static const int n8 = 0x38;
  static const int n9 = 0x39;

  static const int COLON = 0x3A; // ':'
  static const int SEMICOLON = 0x3B; // ';'
  static const int LESSTHAN = 0x3C; // '<'
  static const int EQUALS = 0x3D; // '='
  static const int GREATERTHAN = 0x3E; // '>'
  static const int QUESTION = 0x3F; // '?'
  static const int AT = 0x40; // '@'

  static const int A = 0x41;
  static const int B = 0x42;
  static const int C = 0x43;
  static const int D = 0x44;
  static const int E = 0x45;
  static const int F = 0x46;
  static const int G = 0x47;
  static const int H = 0x48;
  static const int I = 0x49;
  static const int J = 0x4A;
  static const int K = 0x4B;
  static const int L = 0x4C;
  static const int M = 0x4D;
  static const int N = 0x4E;
  static const int O = 0x4F;
  static const int P = 0x50;
  static const int Q = 0x51;
  static const int R = 0x52;
  static const int S = 0x53;
  static const int T = 0x54;
  static const int U = 0x55;
  static const int V = 0x56;
  static const int W = 0x57;
  static const int X = 0x58;
  static const int Y = 0x59;
  static const int Z = 0x5A;

  static const int SQUAREOPENBRACKET = 0x5B; // '['
  static const int BACKSLASH = 0x5C; // '\'
  static const int SQUARECLOSEBRACKET = 0x5D; // ']'
  static const int CARET = 0x5E; // '^'
  static const int UNDERSCORE = 0x5F; // ''
  static const int GRAVEACCENT = 0x60; // '`'

  static const int a = 0x61;
  static const int b = 0x62;
  static const int c = 0x63;
  static const int d = 0x64;
  static const int e = 0x65;
  static const int f = 0x66;
  static const int g = 0x67;
  static const int h = 0x68;
  static const int i = 0x69;
  static const int j = 0x6A;
  static const int k = 0x6B;
  static const int l = 0x6C;
  static const int m = 0x6D;
  static const int n = 0x6E;
  static const int o = 0x6F;
  static const int p = 0x70;
  static const int q = 0x71;
  static const int r = 0x72;
  static const int s = 0x73;
  static const int t = 0x74;
  static const int u = 0x75;
  static const int v = 0x76;
  static const int w = 0x77;
  static const int x = 0x78;
  static const int y = 0x79;
  static const int z = 0x7A;

  static const int CURLYOPENBRACKET = 0x7B; // '{'
  static const int VERTICALBAR = 0x7C; // '|'
  static const int CURLYCLOSEBRACKET = 0x7D; // '}'
  static const int TILDE = 0x7E; // '~'
  static const int DEL = 0x7F;

  static const int D0 = -48;
}
